In [7]:
from data import fatec_operacao, fatec_pagamento, fatec_movimento

In [4]:
import pandas as pd

In [2]:
fatec_operacao

,id_opr_cad_pos,doc_cli,tip_cli,qtd_pcl,dat_vct_ult_pcl,vlr_ctrd_fta_tfm,sdo_ddr_tfm,vlr_ctrd,id_ult_rss_opr,id_mdl,cod_mdl,id_fnt
0,0f503289-dfb,87308050371,F,52.0,20112023.0,NaN,259741.1685,28511582.70,25e351cc-ec4e-4a47-861e-834f2aa1dc13,14,C01,88
1,683ea107-f2e,54355614187,F,36.0,6112022.0,140141.5236,NaN,NaN,a1f18524-8a4f-40a5-ba31-6fbff83bfd58,10,B05,88
2,d8e48899-58d,92265948819,F,NaN,NaN,NaN,0.0000,NaN,63149b03-b3bd-41e3-9b33-86661155bbaf,15,D01,88
3,5909262c-526,104455393515,F,82.0,20112019.0,NaN,1520.5905,27626512.71,40367466-b381-4452-add6-641eafb6b1be,14,C01,88
4,a2baadcc-95a,8642684152,F,65.0,15042020.0,NaN,8093.7615,26287450.65,3e99353c-df9a-4164-831d-84fff45cefdf,14,C01,88
...,...,...,...,...,...,...,...,...,...,...,...,...
2995,11bd0eb8-546,213603194469,F,NaN,NaN,NaN,2115.0240,NaN,e6c5bd30-c23a-4134-b733-c3546e9981bb,15,D01,298
2996,38634b0a-897,252169585344,F,60.0,25112018.0,145296.1440,NaN,NaN,2274cb1f-602b-4761-bea5-2ef420154a90,10,B05,298
2997,cebe727e-8b5,247391528715,F,84.0,10092026.0,NaN,187834.5642,20333074.29,5da63c6a-28be-48e4-8a4a-f71bce8a4a53,14,C01,298
2998,e6965bba-e4a,249677066973,F,47.0,10122021.0,NaN,48979.6941,30874638.30,adbd7ce7-c890-4f12-a581-7c64db1af242,14,C01,298
2999,a5d43fa5-536,258481778859,F,36.0,30042021.0,74816.1801,NaN,NaN,8340c27b-499e-4147-9d29-7268db9bd3bc,10,B05,298

In [6]:
fatec_operacao.to_excel("dados/importados/fatec_opr.xlsx", sheet_name = "tabela 1", index = False)

In [13]:
if 'jose' in fatec_operacao:
    print("TEM")
else:
    print("Fudeo")

Fudeo

In [14]:
fatec_movimento.head()

,id_opr_cad_pos,id_mvt_cad_pos,dat_vct,qtd_pcl_vnc,qtd_pcl_pgr,vlr_tot_fat_tfm,vlr_min_fat_tfm,vlr_pcl_tfm,tip_mvt,prd,id_fnt,cod_mdl
0,ed78c2f2-fd2,64d85edf-8b3,15062019,NULL,NULL,NULL,NULL,2728.3476,ANT,M,88,B05
1,84706050-586,3e537b64-340,10042019,NULL,NULL,2195.7135,329.3049,NULL,ANT,NULL,7,D01
2,7b3bc686-d7f,930e64c5-777,17022019,NULL,NULL,3791.8644,56870.4600,NULL,ANT,NULL,953,D01
3,57a7735b-83e,79bac911-7a0,10022019,NULL,NULL,NULL,NULL,1284.6519,ANT,M,781,C01
4,c527b570-ce7,81c011a3-349,10102019,NULL,NULL,647.3508,540.4320,NULL,ANT,NULL,781,D01

In [ ]:
def consistencia(series_base, series_referencia, fonte):